### ISSUE TITLE
Summary

### ISSUE THREAD

**Issue by farishkash** [agrajalesh/prj-rev-bwfs-dasmoto#4]
Overall met expectations.

In this first submission I look for two items.

Did you use divs, classes/ids to organize your content and apply styles.
You were good on divs and ids, but you should use classes instead of inline styles.  For example if this was a larger store and you had a few 100 prices, a class you would only have to change once inside of the css file.  Inline styling you have go to each element and change it directly.

Second is your css efficient and non repetitive.
CSS is fine, I just pointed out a more efficient way to apply font family to the whole page.

To prepare you for the upcoming projects I like you to go to flexboxfroggy.com. See how far you can get, the later projects uses flexbox heavily and this will help you immensely.

**Comment by agrajalesh** [comment]
Thanks a lot for your comments. I will review my program according your suggestions. 
in the last three days I had some difficulties to be in the course.

**Comment by agrajalesh** [comment]
Hi farishkash, 
please, could you check mi project again in order to know if I understood your corrections instructions? 
Thanks in advance for your help.
